name:                rule-lang
version:             0.1.0.0
github:              "runeksvendsen/rule-lang"
license:             MIT
license-file:        LICENSE
author:              "Rune K. Svendsen"
maintainer:          "runesvend@gmail.com"

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall

default-extensions:
  - OverloadedStrings
  - StandaloneDeriving
  - DeriveGeneric
  - NoImplicitPrelude
  - FlexibleContexts

library:
  source-dirs: src
  dependencies:
    - text
    - unordered-containers
    - aeson
    - hashable
    - transformers
    - errors
    - protolude
    - containers
    - megaparsec
    - parser-combinators
    - parsers
    - template-haskell
    - QuickCheck  # Examples.Test.Pos
    - pretty-show # TEMPORARY
    - deepseq # benchmark

executables:
  rule-lang-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - rule-lang
      - text
      - bytestring
      - aeson
      - unordered-containers  # Output
      - hashable              # Output
      - pretty-show
      - megaparsec

tests:
  rule-lang-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - rule-lang
      - megaparsec
      - smallcheck
      - transformers
      - tasty
      - tasty-smallcheck
      - text
      # HSpec
      - hspec
      - hspec-smallcheck
      - hspec-expectations-pretty-diff
      - hedgehog
      - pretty-show
      - unordered-containers
      - aeson # For generating test positions
      - QuickCheck
      - text-ansi # Terminal colors
    ghc-options:
      - -O2

benchmarks:
  rule-lang-bench:
    main:         Main.hs
    source-dirs:  bench
    dependencies:
    - rule-lang
    - criterion
    - QuickCheck
    - deepseq
    ghc-options:
      - -O2
