name:                rule-lang
version:             0.1.0.0
github:              "runeksvendsen/rule-lang"
license:             MIT
license-file:        LICENSE
author:              "Rune K. Svendsen"
maintainer:          "runesvend@gmail.com"

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall

default-extensions:
  - OverloadedStrings
  - StandaloneDeriving
  - DeriveGeneric
  - NoImplicitPrelude
  - FlexibleContexts

library:
  source-dirs: src
  dependencies:
    - text
    - unordered-containers
    - aeson
    - hashable
    - transformers
    - errors
    - protolude
    - containers
    - megaparsec

executables:
  rule-lang-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - rule-lang
      - text
      - bytestring
      - aeson
      - unordered-containers  # Output
      - hashable              # Output
